export { default as TricyclesCreate} from "./TricyclesCreate"
export { default as TricyclesEdit} from "./TricyclesEdit"
export { default as TricyclesList} from "./TricyclesList"
export { default as TricyclesShow} from "./TricyclesShow"
export { default as TricycleLinkField} from "./TricycleLinkField"
